import {
  Numbers,
  Operator,
  SpecialKeys,
  keyboard,
  resultsScreen,
} from "../src";

(function () {
  keyboard.pressKey(Numbers.FOUR);
  keyboard.pressKey(Numbers.EIGHT);
  keyboard.pressKey(Operator.ADD);
  keyboard.pressKey(Numbers.FIVE);
  keyboard.pressKey(Numbers.TWO);
  keyboard.pressKey(Operator.MULTIPLY);
  keyboard.pressKey(Numbers.TWO);
  keyboard.pressKey(Operator.DIVIDE);
  keyboard.pressKey(Numbers.FOUR);
  keyboard.pressKey(Operator.SUBTRACT);
  keyboard.pressKey(Numbers.TWO);
  console.log("Calculator");
  console.log(resultsScreen.current);
  keyboard.pressKey(Operator.EQUAL);
  console.log("final result => ", resultsScreen.current);
  console.log(resultsScreen.history);
  keyboard.pressKey(Operator.ADD);
  keyboard.pressKey(Numbers.TWO);
  console.log("Calculator");
  console.log(resultsScreen.current);
  keyboard.pressKey(Operator.EQUAL);
  console.log("final result => ", resultsScreen.current);
  console.log(resultsScreen.history);
  keyboard.pressKey(SpecialKeys.CLEAR);
  keyboard.pressKey(Numbers.FIVE);
  keyboard.pressKey(Operator.ADD);
  keyboard.pressKey(Numbers.FIVE);
  keyboard.pressKey(Operator.EQUAL);
  console.log("Calculator");
  console.log("final result => ", resultsScreen.current);
  console.log(resultsScreen.current);
  keyboard.pressKey(Operator.EQUAL);
  keyboard.pressKey(Operator.EQUAL);
  keyboard.pressKey(Operator.EQUAL);
  console.log("final result => ", resultsScreen.current);
  console.log(resultsScreen.history);
  keyboard.pressKey(Numbers.ONE);
  keyboard.pressKey(Numbers.ZERO);
  console.log(resultsScreen.current);
  keyboard.pressKey(Operator.EQUAL);
  keyboard.pressKey(Operator.DIVIDE);
  keyboard.pressKey(Numbers.THREE);
  console.log("Calculator");
  console.log("final result => ", resultsScreen.current);
  keyboard.pressKey(Operator.EQUAL);
  console.log("final result => ", resultsScreen.current);
  console.log(resultsScreen.history);
  keyboard.pressKey(SpecialKeys.CLEAR);
  console.log("Calculator");
  console.log("final result => ", resultsScreen.current);
  console.log(resultsScreen.history);
  keyboard.pressKey(Numbers.FOUR);
  keyboard.pressKey(Numbers.EIGHT);
  keyboard.pressKey(Operator.MULTIPLY);
  keyboard.pressKey(Numbers.ONE);
  keyboard.pressKey(Numbers.FIVE);
  keyboard.pressKey(Numbers.ZERO);
  keyboard.pressKey(Numbers.ZERO);
  keyboard.pressKey(Operator.PERCENTAGE);
  keyboard.pressKey(Operator.EQUAL);
  console.log("Calculator");
  console.log("final result => ", resultsScreen.current);
  console.log(resultsScreen.history);
  keyboard.pressKey(SpecialKeys.CLEAR);
  console.log("Calculator");
  console.log("final result => ", resultsScreen.current);
  console.log(resultsScreen.history);
  keyboard.pressKey(Numbers.ONE);
  keyboard.pressKey(Numbers.ZERO);
  keyboard.pressKey(SpecialKeys.AMBIGUITY);
  keyboard.pressKey(Operator.MULTIPLY);
  keyboard.pressKey(Numbers.TWO);
  console.log("Calculator");
  console.log("final result => ", resultsScreen.current);
  console.log(resultsScreen.history);
  keyboard.pressKey(Operator.EQUAL);
  console.log("Calculator");
  console.log("final result => ", resultsScreen.current);
  console.log(resultsScreen.history);
  keyboard.pressKey(SpecialKeys.CLEAR);
  keyboard.pressKey(Numbers.ONE);
  keyboard.pressKey(SpecialKeys.DOT);
  keyboard.pressKey(Numbers.FIVE);
  keyboard.pressKey(Operator.ADD);
  keyboard.pressKey(Numbers.THREE);
  keyboard.pressKey(Operator.EQUAL);
  console.log("Calculator");
  console.log("final result => ", resultsScreen.current);
  console.log(resultsScreen.history);
  keyboard.pressKey(SpecialKeys.CLEAR);
  keyboard.pressKey(Numbers.ONE);
  keyboard.pressKey(Numbers.ZERO);
  keyboard.pressKey(SpecialKeys.DOT);
  keyboard.pressKey(Numbers.FIVE);
  keyboard.pressKey(Operator.MULTIPLY);
  keyboard.pressKey(Numbers.THREE);
  keyboard.pressKey(Operator.EQUAL);
  console.log("Calculator");
  console.log("final result => ", resultsScreen.current);
  console.log(resultsScreen.history);
})();
